competition/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.home_page, name='home'),
    path('rules/', views.rules_page, name='rules'),
    path('enter/', views.enter_submit, name='enter'),
    path('edit/<slug:slug>', views.edit_entry, name='edit_entry'),
    path('delete/<slug:slug>', views.delete_entry, name='delete_entry'),
    path('all_entries/', views.EntriesList.as_view(), name='all_entries'),
    path('competition/', views.CurrentOrderList.as_view(), name='competition'),
    path('<slug:slug>/', views.EntryDetail.as_view(), name='entry_detail'),
    path('like/<slug:slug>', views.EntryLike.as_view(), name='entry_like')
]

dogshow/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('competition.urls'), name='competition_urls'),
    path('accounts/', include('allauth.urls')),
]

handler404 = "dogshow.views.page_not_found_view"

competition/models.py
"""
Database models for the dogshow app
& comments section.
"""
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.utils.text import slugify

STATUS = ((0, 'Draft'), (1, 'Published'))


# Model created with the help of "I think therefore I blog"
class Enter(models.Model):
    """
    Database model for submitting an entry
    """
    title = models.CharField(
        max_length=200, unique=True, null=False, blank=False)
    slug = models.SlugField(
        max_length=200, unique=True, null=False, blank=False)
    competitor = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='post_enter')
    content = models.TextField()
    featured_image = CloudinaryField('image', null=False, blank=False)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(User, related_name='post_likes', blank=True)

    class Meta:
        """
        To display entries in descending order
        """
        ordering = ['-created_on']

    def save(self, *args, **kwargs):
        """
        Auto populate slug field
        """
        self.slug = slugify(self.title)
        super(Enter, self).save(*args, **kwargs)

    def __str__(self):
        """
        To return a string representation of an object
        """
        return self.title

    def number_of_likes(self):
        """
        Return total number of entry likes
        """
        return self.likes.count()


# Model used from "I think therefore I blog" walkthrough.
class Comment(models.Model):
    """
    Database model for creating a comment
    on an entry
    """
    post = models.ForeignKey(
        Enter, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        """
        Order comments in ascending order
        """
        ordering = ['created_on']

    def __str__(self):
        """
        Display the comment as the comment text,
        and comment author name
        """
        return f'Comment {self.body} by {self.name}'

competition/forms.py
from .models import Comment, Enter
from django import forms


class EnterForm(forms.ModelForm):
    """
    Entry submission form
    """
    class Meta:
        model = Enter
        fields = (
            'title',
            'content',
            'featured_image',
        )


class CommentForm(forms.ModelForm):
    """
    Comment submission form
    """
    class Meta:
        model = Comment
        fields = ('body',)

competition/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.views import generic, View
from django.http import HttpResponseRedirect
from django.db.models import Count
from .models import Enter
from django.contrib import messages
from .forms import CommentForm, EnterForm


def home_page(request):
    """
    View for home page.
    """
    return render(request, 'index.html')


def rules_page(request):
    """
    View for rules page.
    """
    return render(request, 'rules.html')


def enter_page(request):
    """
    View for Enter page.
    """
    return render(request, 'enter.html')


class EntriesList(generic.ListView):
    """
    View for All Entries page.
    """
    model = Enter
    queryset = Enter.objects.filter(status=1).order_by('-created_on')
    template_name = 'all_entries.html'
    paginate_by = 12


# Class created using help from StackOverflow.
class CurrentOrderList(generic.DetailView):
    """
    View for Competition page.
    Lists entry with most liked at the top.
    """
    model = Enter
    queryset = (
        Enter.objects.filter(status=1)
        .alias(nlikes=Count('likes'))
        .order_by('-nlikes')
    )
    template_name = 'competition.html'

    def get_object(self, *args, **kwargs):
        """
        Show only entry with most likes.
        """
        return self.get_queryset().first()


# Class used from "I think therefore I blog" walkthrough.
class EntryDetail(View):
    """
    Render the individual entry
    to the browser.
    """
    def get(self, request, slug, *args, **kwargs):
        """
        Create a new URL path for each blog post.
        Create a comments section on the page.
        """
        queryset = Enter.objects.filter(status=1)
        entry = get_object_or_404(queryset, slug=slug)
        comments = entry.comments.filter(approved=True).order_by('created_on')
        liked = False
        if entry.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            'entry_detail.html',
            {
                'entry': entry,
                'comments': comments,
                'commented': False,
                'liked': liked,
                'comment_form': CommentForm()
            }
        )

    def post(self, request, slug, *args, **kwargs):
        """
        Submit a new comment to an entry.
        """
        queryset = Enter.objects.filter(status=1)
        entry = get_object_or_404(queryset, slug=slug)
        comments = entry.comments.filter(approved=True).order_by('created_on')
        liked = False
        if entry.likes.filter(id=self.request.user.id).exists():
            liked = True

        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.post = entry
            comment.save()
        else:
            comment_form = CommentForm()

        return render(
            request,
            'entry_detail.html',
            {
                'entry': entry,
                'comments': comments,
                'commented': True,
                'liked': liked,
                'comment_form': CommentForm()
            }
        )


# Class used from "I think therefore I blog" walkthrough.
class EntryLike(View):
    """
    Allow a user to like an entry
    """
    def post(self, request, slug):
        """
        Check if user already liked the entry.
        Allow like/unlike accordingly.
        """
        entry = get_object_or_404(Enter, slug=slug)

        if entry.likes.filter(id=request.user.id).exists():
            entry.likes.remove(request.user)
        else:
            entry.likes.add(request.user)

        return HttpResponseRedirect(reverse('entry_detail', args=[slug]))


# Function built using instructions from "Hello Django",
# "I think therefore I blog",
# a previous generation fellow student - credited in README.
def enter_submit(request):
    """
    View for Enter page.
    """
    if request.method == 'POST':
        enter_form = EnterForm(request.POST, request.FILES)
        if enter_form.is_valid():
            enter_form.instance.competitor = request.user
            enter_form.save()
            return redirect('all_entries')
        else:
            enter_form = EnterForm()

    return render(
        request,
        'enter.html',
        {
            'enter_form': EnterForm(),
        },
    )


def edit_entry(request, slug):
    """
    Edit a submitted entry
    """
    entry = get_object_or_404(Enter, slug=slug)
    edit_form = EnterForm(request.POST or None, instance=entry)
    context = {
        'edit_form': edit_form,
        'entry': entry
    }

    if request.method == 'POST':
        edit_form = EnterForm(
            request.POST, request.FILES, instance=entry)
        if edit_form.is_valid():
            entry = edit_form.save(commit=False)
            entry.competitor = request.user
            entry.save()
            return redirect('all_entries')
    else:
        edit_form = EnterForm(instance=entry)

    return render(request, 'edit_entry.html', context)


# Instructed by "Hello Django"
def delete_entry(request, slug):
    """
    Delete a submitted entry
    """
    entry = get_object_or_404(Enter, slug=slug)
    entry.delete()
    return redirect('all_entries')

templates/about.html
{% extends "base.html" %}

{% block content %}


<div class="container login-form-container">
    <div class="row justify-content-center">
        <div class="col-sm-6 mt-4 login-form">
            <div class="card-body">
                <p>
                    Welcome the Online Dog Show!
                </p>
                <p>
                    To be able to enter the competition, you need to log in to the site with your account. If you do not
                    have an account created, navigate to sign-up page and create one.
                </p>
                <p>
                    Once that is done, click on “Enter” tab and post your best photo of your best friend. Before any
                    entry is published, it is reviewed by the admin to make sure it is user friendly.
                </p>
                <p>
                    Under “All Entries” tab, you can view all the entries and like ones you think deserve a like. You
                    can also comment on them to express your admiration with words. All comments will be reviewed by
                    admin before being published to make sure they are user friendly.
                </p>
                <p>
                    Navigating to “Competition” tab, you can see the entry with most likes.
                </p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/all_entries.html
{% extends "base.html" %}

{% load cloudinary %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for entry in enter_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <a href="{% url 'entry_detail' entry.slug %}">
                                <div>
                                    <img class="card-img-top" src="{{ entry.featured_image.url }}"
                                        alt="{{ entry.title }}">
                                    <div>
                                        <p class="competitor text-muted">By: {{ entry.competitor }}</p>
                                    </div>
                                </div>
                                <h2 class="card-title">{{ entry.title }}</h2>
                            </a>
                            <hr>
                            <p class="card-text text-muted h6">{{ entry.created_on}} <i class="far fa-heart"></i>
                                {{ entry.number_of_likes }}</p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Online dog photo sharing site to bring dog owners together.">
    <meta name="keywords" content="Online dog show, dog, show, comment, competition, enter">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rowdies:wght@300;400;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <script src="https://kit.fontawesome.com/e7d1b9f4c6.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous">
    </script>
    <title>Online Dog Show</title>
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
</head>

<body>
    <header>
        <div>
            <img class="bg-image" src="{% static 'images/online-dog-show.jpg' %}" alt="Group of dogs sitting in front of a pink wall">
            <div>
                <a class="navbar-brand" href="{% url 'home' %}"><span class="logo">ONLINE<br>DOG<br>SHOW</span></a>
            </div>
        </div>
        <!-- BOOTSTAP NAVIGATION BAR -->
        <div class="bg-nav">
            <nav class="navbar navbar-expand-lg navbar-light bg-light bg-transparent">
                <div class="container-fluid">

                    <button class="navbar-toggler mx-auto" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-icon"><i class="fa-solid fa-bars"></i></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mx-auto fw-bolder">
                            <li class="nav-item active mx-auto bg-transparent fw-bolder">
                                <a class="nav-link align-top" href="{% url 'home' %}">Home</a>
                            </li>
                            <li class="nav-item mx-auto bg-transparent fw-bolder">
                                <a class="nav-link" href="{% url 'rules' %}">Rules</a>
                            </li>

                            {% if user.is_authenticated %}
                            <li class="nav-item mx-auto bg-transparent fw-bolder">
                                <a class="nav-link" href="{% url 'enter' %}">Enter</a>
                            </li>
                            {% endif %}

                            <li class="nav-item mx-auto bg-transparent fw-bolder">
                                <a class="nav-link" href="{% url 'all_entries' %}">All Entries</a>
                            </li>

                            <li class="nav-item mx-auto bg-transparent fw-bolder">
                                <a class="nav-link" href="{% url 'competition' %}">Competition</a>
                            </li>

                            {% if user.is_authenticated %}
                            <li class="nav-item mx-auto bg-transparent fw-bolder">
                                <a class="nav-link" href="{% url 'account_logout' %}">LogOut</a>
                            </li>
                            {% else %}
                            <li class="nav-item mx-auto bg-transparent fw-bolder">
                                <a class="nav-link" href="{% url 'account_login' %}">LogIn/SignIn</a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>

        </div>
    </header>

    <!-- MESSAGES: Used from "I think therefore I blog" -->
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <main>
        {% block content %}
        {% endblock %}
    </main>


    <footer>
        <!--SOCIAL LINKS-->
        <div class="container">
            <div class="row">
                <div class="col social-icons">
                    <ul id="social" class="list-inline">
                        <li class="list-inline-item">
                            <a href="https://facebook.com" target="_blank" rel="noopener"
                                aria-label="Visit our Facebook page (opens in a new tab)">
                                <i class="fa-brands fa-facebook-f"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://twitter.com" target="_blank" rel="noopener"
                                aria-label="Visit our Twitter page (opens in a new tab)">
                                <i class="fa-brands fa-twitter"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://www.instagram.com" target="_blank" rel="noopener"
                                aria-label="Visit our Instagram page (opens in a new tab)">
                                <i class="fa-brands fa-instagram"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://youtube.com" target="_blank" rel="noopener"
                                aria-label="Visit our YouTube page (opens in a new tab)">
                                <i class="fa-brands fa-youtube"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://github.com/DarkoZlatarek" target="_blank" rel="noopener"
                                aria-label="Visit my Github page (opens in a new tab)">
                                <i class="fa-brands fa-github"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://www.linkedin.com/in/darko-zlatarek-890218130/" target="_blank"
                                rel="noopener" aria-label="Visit my Linkedin page (opens in a new tab)">
                                <i class="fa-brands fa-linkedin-in"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- LOCATION & DISCLAIMER -->
        <div class="footer-text">
            <p>Canterbury, United Kingdom<br>Project created for educational purposes only.</p>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous">
    </script>

    <!-- JS for messages taken from "I think therefore I blog" -->
    <script>
        setTimeout(function () {
            let messages = document.getElementById("msg");
            let alert = new bootstrap.Alert(messages);
            alert.close();
        }, 3000);
    </script>

</body>

</html>

templates/competition.html
{% extends "base.html" %}

{% load cloudinary %}

{% block content %}

<div class="container-fluid">
    <div class="row justify-content-center mt-4">
        <div class="col-md-4 align-text card-title">
            <h1>Current leading entry!</h1>
        </div>
        <div class="row justify-content-center mt-4">
            <div class="col-md-4">
                <div class="card mb-4">
                    <div class="card-body">
                        <div>
                            <img class="card-img-top" src=" {{ object.featured_image.url }}" alt="{{ entry.title }}">
                            <div>
                                <p class="competitor text-muted">By: {{ object.competitor }}</p>
                            </div>
                        </div>
                        <h2 class="card-title">{{ object.title }}</h2>
                        <hr>
                        <p class="card-text text-muted h6">{{ object.created_on}} <i class="far fa-heart"></i>
                            {{ object.number_of_likes }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/edit_entry.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}
{% load cloudinary %}

<div class="container form-container">
    <div class="row justify-content-center">
        <div class="col-sm-6 mt-4 form">
            <div class="card-body">
                {% if user.is_authenticated %}

                <h3>Edit your entry:</h3>

                <form method="POST" enctype="multipart/form-data">
                    {{ edit_form | crispy }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-signup btn-lg">Submit</button>
                </form>

                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/enter.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}
{% load cloudinary %}

<div class="container form-container">
    <div class="row justify-content-center">
        <div class="col-sm-6 mt-4 form">
            <div class="card-body">
                {% if user.is_authenticated %}

                <h3>Enter the competition:</h3>

                <form method="POST" enctype="multipart/form-data">
                    {{ enter_form | crispy }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-signup btn-lg">Submit</button>
                    <div class="submit-disclaimer">* Your photo will have to be approved by admin before being
                        published.</div>
                </form>

                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/entry_detail.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-sm-6 mt-4 form">
            <div class="card-body">
                <h1 class="card-title">
                    {{ entry.title }}
                </h1>
                <p class="card-text"> {{ entry.competitor }} | {{ entry.created_on }}</p>
            </div>
            <div class="col">
                <img class="entry-detail-img-width" src="{{ entry.featured_image.url }}" alt="{{ entry.title }}">
            </div>

            {% if request.user == entry.competitor %}
            <div>
                <hr>
                <div class="modal-box d-flex justify-content-center">
                    <a href="{% url 'edit_entry' entry.slug %}" class="btn btn-signup">Edit</a>

                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-signup btn-delete" data-bs-toggle="modal"
                        data-bs-target="#staticBackdrop">
                        Delete
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false"
                        tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="staticBackdropLabel">Are you sure you want to delete
                                        your entry?</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                                </div>
                                <div class="modal-footer justify-content-center">
                                    <button type="button" class="btn btn-signup" data-bs-dismiss="modal">Don't
                                        delete</button>
                                    <a href="{% url 'delete_entry' entry.slug %}" class="btn btn-secondary">Yes,
                                        delete!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
    <div class="row justify-content-center">
        <div class="col-md-8 mt-3">

            <div class="card-body">
                <p class="card-text align-text">{{ entry.content | safe }}</p>
            </div>

            <div class="row justify-content-center mt-3">
                <div class="col-3">
                    <div class="offset-md-5">
                        {% if user.is_authenticated %}
                        <form class="d-inline" action="{% url 'entry_like' entry.slug %}" method="POST">
                            {% csrf_token %}

                            {% if liked %}

                            <button class="button-like" type="submit" name="entry_id" value="{{ entry.slug }}"><i
                                    class="fa-solid fa-heart fa-lg"></i></button>

                            {% else %}

                            <button class="button-like" type="submit" name="entry_id" value="{{ entry.slug }}"><i
                                    class="fa-regular fa-heart fa-lg"></i></button>

                            {% endif %}
                        </form>

                        {% else %}

                        <span class="button-like"><i class="fa-regular fa-heart fa-lg"></i></span>

                        {% endif %}

                        <span>{{ entry.number_of_likes }}</span>
                    </div>
                </div>
                <div class="col-3">
                    {% with comments.count as total_comments %}
                    <strong class="offset-md-4 comment-fa"><i class="far fa-comments fa-lg"></i>
                        {{ total_comments }}
                    </strong>
                    {% endwith %}
                </div>
            </div>


        </div>
    </div>
</div>
<hr>

<!-- Comments section -->

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 card mb-4 mt-3 ">
            <h3 class="card-text">Comments:</h3>
            <div class="card-body">
                {% for comment in comments %}
                <div class="card comment-bg">
                    <p class="card-text name-relative">
                        {{ comment.name }}
                        <span class="comment-time">
                            {{ comment.created_on }}
                        </span>
                    </p>
                    <span class="text-muted">
                        {{ comment.body | linebreaks }}
                    </span>
                </div>
                {% endfor %}
            </div>

            <div>
                <div class="card-body">
                    {% if commented %}
                    <div class="alert alert-success" role="alert">
                        Your comment is awaiting approval
                    </div>
                    {% else %}

                    {% if user.is_authenticated %}
                    <hr>
                    <h3>Leave a comment:</h3>
                    <p>Posting as: {{ user.username }}</p>
                    <form method="POST">
                        {{ comment_form | crispy }}
                        {% csrf_token %}
                        <button type="submit" class="btn btn-signup btn-lg">Submit</button>
                    </form>
                    {% endif %}
                    {% endif %}
                </div>
            </div>

        </div>

    </div>
</div>

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="container form-container">
    <div class="row justify-content-center">
        <div class="col-sm-6 mt-4 form">
            <div class="card-body">
                <p>
                    Welcome to the Online Dog Show!
                </p>
                <p>
                    This is a friendly webpage where you can share the photo of your dog with others, discuss about the
                    breed or anything else through comments, find friends, but also there is a little competition on who
                    gets most likes for their dog.
                </p>
                <p>
                    Enjoy!
                </p>
            </div>
        </div>
    </div>
</div>

{% endblock %}